---
- name: Get basic remote hosts os info
  hosts: all
  become: true
  tasks:
    - name: Verify the host is RedHat family and version 8
      when:
        - ansible_os_family == "RedHat"
        - ansible_distribution_major_version == "8"
      debug:
        msg: "Well done! Your machine is {{ ansible_os_family }} and version {{ ansible_distribution_major_version }}"
      failed_when: false
    
    - name: Fail if conditions are not met
      fail:
        msg: "The remote host {{ inventory_hostname }} does not meet the required criteria."
      when: not (ansible_os_family == "RedHat" and ansible_distribution_version == "8")