---
- name: New version of install crystaldb for testing
  hosts: all
  become: true
  become_method: sudo
  tasks:
    - name: Install the repository RPM
      ansible.builtin.dnf: 
        disable_gpg_check: true
        name: "https://dl.crystaldb.com/yum/noarch/crystaldb-repo-1.0-1.el8.noarch.rpm"
        state: present
    
    - name: Disable PostgreSQL related module
      ansible.builtin.dnf:
        name: postgresql
        autoremove: false
        state: absent


    - name: Install crystaldb
      command: dnf install -y crystaldb15-server crystaldb15-contrib citus pg_cron_15 orafce_15 count_distinct_15 multicorn2_15 passwordcheck_cracklib_15 periods_15 pg_bulkload_15 pg_checksums_15 pg_top_15 pgagent_15 pgaudit17_15 pgcopydb_15 pglogical_15 crystaldb15-odbc


    - name: Install Utils package
      ansible.builtin.package:
        name: python3-psycopg2
        state: present
    
    - name: Check if CrystalDB is Initialize
      ansible.builtin.stat:
        path: "/var/lib/crys/15/data/pg_hba.conf"
      register: crystaldb_data
    
    - name: Initialize the database
      command: "/opt/CrystalDB/pgsql-15/bin/crystaldb-15-setup initdb"
      when: not crystaldb_data.stat.exists

    - name: Enable and start PostgreSQL service
      service:
        name: crystaldb-15
        state: started
        enabled: true
