---
- name: Create a new PostgreSQL user with Superuser privilege
  hosts: remote_hosts
  become: true
  vars:
    new_db_user: crystal
    new_user_password: crystal
  tasks:
    - name: Check utility package is installed
      ansible.builtin.package:
        name: python3-psycopg2
        state: present

    - name: Print basic information that we are gonna create in CrystalDB
      ansible.builtin.debug:
        msg: "We are gonna create: {{ new_db_user }} with password: {{ new_user_password }} in CrystalDB"
    
    - name: Create a new PostgreSQL user with password and Superuser privileges
      community.postgresql.postgresql_user:
        state: present
        name: "{{ new_db_user }}"
        password: "{{ new_user_password }}"
        role_attr_flags: SUPERUSER
        login_port: 5555
      become: true
      become_user: postgres