---
- name: Testing semaphore connection
  hosts: all
  gather_facts: false
  tasks:
    - name: testing ping
      ping:
      
    - name: Filter and return only selected facts
      ansible.builtin.setup:
